name: Deploy Dev build to Firebase

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  build_and_deploy_android:
    name: Build & Deploy Dev
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches/modules-*
            ~/.gradle/caches/jars-*
            ~/.gradle/caches/build-cache-*
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up signing properties
        env:
          SIGNING_PROPERTIES: ${{ secrets.SIGNING_PROPERTIES }}
        run: |
          echo -e "$SIGNING_PROPERTIES" >> signing.properties

      - name: Set up dev properties
        env:
          ENV_PROPERTIES: ${{ secrets.ENV_PROPERTIES }}
        run: |
          echo -e "$ENV_PROPERTIES" > dev.properties

      - name: Set up Google Services json
        env:
          FIREBASE_GOOGLE_SERVICES_JSON: ${{ secrets.FIREBASE_GOOGLE_SERVICES_JSON }}
        run: |
          echo "$FIREBASE_GOOGLE_SERVICES_JSON" > app/google-services.json
          # ตรวจสอบว่าไฟล์ถูกสร้างและมีเนื้อหาถูกต้อง
          cat app/google-services.json
          # ตรวจสอบ JSON syntax
          python3 -m json.tool app/google-services.json || echo "Invalid JSON format in google-services.json"

      - name: Set up New Relic properties
        env:
          NEWRELIC_PROPERTIES: ${{ secrets.NEWRELIC_PROPERTIES }}
        run: |
          echo -e "$NEWRELIC_PROPERTIES" > app/newrelic.properties

      - name: Bump version code
        run: |
          perl -i -pe 's/ANDROID_VERSION_CODE =(.*)$/ANDROID_VERSION_CODE = ${{github.run_number}}/g' buildSrc/src/main/java/Versions.kt

      - name: Build debug APK
        run: ./gradlew assembleRelease --stacktrace  # เพิ่ม --stacktrace เพื่อดู error

      - name: Generate release notes
        id: generate-release-notes
        run: |
          echo "RELEASE_NOTE_CONTENT=$(git log -1 | grep -o "\[.*")" >> $GITHUB_OUTPUT

      - name: Deploy Android to Firebase
        uses: wzieba/Firebase-Distribution-Github-Action@v1.5.0
        with:
          appId: ${{ secrets.FIREBASE_ANDROID_APP_ID }}
          serviceCredentialsFileContent: ${{ secrets.FIREBASE_DISTRIBUTION_CREDENTIAL_JSON }}
          groups: ${{ secrets.FIREBASE_DISTRIBUTION_TESTER_GROUPS }}
          file: app/build/outputs/apk/release/app-release-unsigned.apk
          releaseNotes: ${{ steps.generate-release-notes.outputs.RELEASE_NOTE_CONTENT }}