name: CI Pipeline

on:
  push:
    branches:
      - '*'
      - '!develop'  # ข้าม develop ถ้าไม่ต้องการรันตอน push ปกติ
  pull_request:
    branches:
      - develop
      - main  # เพิ่ม main เพื่อให้ครอบคลุม PR เข้า main

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run ktlint
        run: ./gradlew ktlintCheck

      - name: Run detekt
        run: ./gradlew detekt

      - name: Run tests and generate coverage with Kover
        run: ./gradlew test koverReport

      - name: Upload Kover Report
        uses: actions/upload-artifact@v3
        with:
          name: kover-report
          path: app/build/reports/kover/

  ai-code-review:
    needs: lint-and-test
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: AI Code Review
        uses: github/codeql-action/analyze@v2
        with:
          category: "AI-Review"

      - name: Auto Approve PR
        if: success()
        uses: hmarr/auto-approve-action@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

  build-and-deploy:
    needs: ai-code-review
    if: (github.event_name == 'pull_request' && github.event.pull_request.merged == true) || github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build APK
        run: ./gradlew assembleDebug

      - name: List APK files (Debugging)
        run: ls -la app/build/outputs/apk/debug/

      - name: Upload APK to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.FIREBASE_APP_ID }}
          serviceCredentialsFileContent: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
          groups: testers
          file: app/build/outputs/apk/debug/app-debug.apk